services:
  database:
    image: bitnami/mysql:latest  # Docker image for MySQL
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: todoAPP
      MYSQL_USER: todo
      MYSQL_PASSWORD: root
    ports:
      - 22212:3306
    volumes:
      - ./db/my.cnf:/etc/mysql/my.cnf  # Correct volume mapping

