spring:
  application:
    name: demo-spring-boot-hibernate-jpa

  datasource:
    url: jdbc:mysql://localhost:22212/todoAPP
    username: todo
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
    hibernate:
      ddl-auto: create-drop

  mail:
    host: smtp.gmail.com
    port: 25
    username: ikdinobi@gmail.com
    password: msxbjiznjitpsjxd
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            ssl:
              enable: true

server:
  port: 8082

#------------------------please revert back to the configuration above before pushing--------------------

#spring:
#  application:
#    name: demo-spring-boot-hibernate-jpa
#
#  datasource:
#    url: jdbc:mysql://localhost:3306/todoAPP
#    username: root
#    password: root
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#        format_sql: true
#    hibernate:
#      ddl-auto: create-drop
#
#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ikdinobi@gmail.com
#    password: msxbjiznjitpsjxd
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            ssl:
#              enable: true
#
#server:
#  port: 8082